# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harringa.com
description: >
  Generally used as a playground for Justin Harringa but also includes
  blog posts. Of course, all of that is subject to change.
baseurl: ""
url: "http://harringa.com"
twitter_username: justinharringa
github_username: justinharringa
permalink: /posts/:year/:month/:day/:title/
author:
  name: "Justin Harringa"

# Build settings
markdown: kramdown

gems: 
  - jekyll-feed
